[package]
name = "thor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.162"
serde_derive = "1.0.162"
serde_with = "3.0.0"
uuid = { version = "1.3.2", features = [ "serde" ] }

