/*
 * Thunderstore API
 *
 * Schema is automatically generated and not completely accurate.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct OwLoginResponseBody {
    #[serde(rename = "session_id")]
    pub session_id: String,
    #[serde(rename = "username")]
    pub username: String,
}

impl OwLoginResponseBody {
    pub fn new(session_id: String, username: String) -> OwLoginResponseBody {
        OwLoginResponseBody {
            session_id,
            username,
        }
    }
}


