name: build

on:
  - push

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        version: [ latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1
      - uses: xmake-io/github-action-setup-xmake@master
        with:
          xmake-version: ${{ matrix.version }}
      - name: Run tests
        run: |
          xmake --version
          xmake config -v -y --mode=debug --toolchain=clang
          xmake -vw
          xmake run ThorCLI -- update -f
